### PR TITLE
add googletranslate.py (command-line version)

### PR DESCRIPTION
**Pull request by syc728**

### CODE REVIEW

**Comment by syc728** [comment]
@ab-anand Please check the script and README.md

**Comment by syc728** [comment]
Python script to translate words (command-line version) via Google Translate. Please check the script and README.md. @ab-anand #2

**Review by ab-anand — APPROVED** [review]
Thanks for the PR @syc728

**Comment by syc728** [comment]
@ab-anand Please also add hacktoberfest tag for the PR, or else it is not valid.

**Pull request merged**
